export const SEARCH = 'SEARCH';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEM_FETCH_BY_ID_SUCCESS = 'ITEM_FETCH_BY_ID_SUCCESS';
export const MODIFY_CUR_SEARCH_FILTER = 'MODIFY_CUR_SEARCH_FILTER';
export const SET_SORTING = 'SET_SORTING';
export const MODIFY_CUR_SEARCH_TEXT = 'MODIFY_CUR_SEARCH_TEXT';
export const FETCH_FILM_BY_ID = 'FETCH_FILM_BY_ID';
export const FETCH_FILMS = 'FETCH_FILMS';

